# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Download_and_combine.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader_Dialog(object):
    def setupUi(self, Downloader_Dialog):
        Downloader_Dialog.setObjectName("Downloader_Dialog")
        Downloader_Dialog.resize(836, 445)
        self.Downloader_GroupBox = QtWidgets.QGroupBox(Downloader_Dialog)
        self.Downloader_GroupBox.setGeometry(QtCore.QRect(20, 20, 801, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Downloader_GroupBox.setFont(font)
        self.Downloader_GroupBox.setObjectName("Downloader_GroupBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.Downloader_GroupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 781, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(self.Downloader_GroupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 390, 791, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Downloader_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Downloader_Dialog)

    def retranslateUi(self, Downloader_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Downloader_Dialog.setWindowTitle(_translate("Downloader_Dialog", "Downloader"))
        self.Downloader_GroupBox.setTitle(_translate("Downloader_Dialog", "Downloader"))
